/* Care to Home Companion - Sample Data from CHOC DC Summary (LL #22: Build Fallback Data) */
/* All data structured as single source of truth (LL #4: One File Per Job) */

const DATA = {

  /* ── Patient Info ── */
  patient: {
    name: { en: 'Amber Rhodes', es: 'Amber Rhodes' },
    age: '2 years old',
    mrn: '768970',
    weight: '13.2 kg',
    allergies: { en: 'None known', es: 'Ninguna conocida' },
    preferredLanguage: 'Mandarin',
    admissionDate: '2026-03-25',
    dischargeDate: '2026-04-01',
    diagnosis: {
      en: 'Type 1 Diabetes - New Onset',
      es: 'Diabetes Tipo 1 - Nuevo Diagnóstico'
    },
    diagnosisPlain: {
      en: 'Your child was diagnosed with Type 1 Diabetes. This means her body can no longer make insulin on its own. She will need insulin every day.',
      es: 'Su hijo/a fue diagnosticado/a con Diabetes Tipo 1. Esto significa que su cuerpo ya no puede producir insulina por sí solo. Necesitará insulina todos los días.'
    },
    condition: { en: 'Good', es: 'Buena' },
    pcp: 'Dr. Sellers',
    consultingPhysicians: ['Dr. Flores, MD'],
    dischargeAuth: 'Dr. Miles, MD',
    diet: {
      en: 'Regular, Age Appropriate',
      es: 'Regular, Apropiada para su Edad'
    },
  },

  /* ── Medications ── */
  medications: [
    {
      id: 'lantus',
      name: 'Insulin glargine (Lantus)',
      namePlain: { en: 'Lantus', es: 'Lantus' },
      dose: '100 units/mL',
      dosePlain: { en: 'As directed by doctor', es: 'Según las indicaciones del médico' },
      route: { en: 'Shot under the skin', es: 'Inyección bajo la piel' },
      frequency: { en: 'Once daily at bedtime', es: 'Una vez al día a la hora de dormir' },
      timeBlock: 'bedtime',
      purpose: {
        en: 'Long-acting insulin that works all day and night to keep blood sugar steady',
        es: 'Insulina de acción prolongada que trabaja todo el día y la noche para mantener el azúcar en la sangre estable'
      },
      icon: 'syringe',
      refills: 2,
      pharmacy: 'Rite Aid Pharmacy #4532',
    },
    {
      id: 'humalog',
      name: 'Insulin lispro (Humalog)',
      namePlain: { en: 'Humalog', es: 'Humalog' },
      dose: '100 units/mL',
      dosePlain: { en: 'Per sliding scale', es: 'Según escala variable' },
      route: { en: 'Shot under the skin', es: 'Inyección bajo la piel' },
      frequency: { en: 'Before each meal', es: 'Antes de cada comida' },
      timeBlock: 'meals',
      purpose: {
        en: 'Fast-acting insulin given before meals to control blood sugar from food',
        es: 'Insulina de acción rápida administrada antes de las comidas para controlar el azúcar en la sangre de los alimentos'
      },
      icon: 'syringe',
      refills: 2,
      pharmacy: 'Rite Aid Pharmacy #4532',
      slidingScale: true,
    },
    {
      id: 'vitamind',
      name: 'Vitamin D3 400 IU drops',
      namePlain: { en: 'Vitamin D3 drops', es: 'Gotas de Vitamina D3' },
      dose: '400 IU',
      dosePlain: { en: '1 mL (one dropper full)', es: '1 mL (un gotero lleno)' },
      route: { en: 'By mouth', es: 'Por la boca' },
      frequency: { en: 'Once daily', es: 'Una vez al día' },
      timeBlock: 'morning',
      purpose: {
        en: 'Helps keep bones strong and supports the immune system',
        es: 'Ayuda a mantener los huesos fuertes y apoya el sistema inmunológico'
      },
      icon: 'droplet',
      refills: 0,
      pharmacy: 'Rite Aid Pharmacy #4532',
    },
  ],

  /* ── Care Instructions (by time of day) ── */
  instructions: {
    morning: [
      {
        id: 'instr-1',
        text: { en: 'Check blood sugar before breakfast', es: 'Revise el azúcar en la sangre antes del desayuno' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-2',
        text: { en: 'Give Humalog shot before breakfast', es: 'Administre la inyección de Humalog antes del desayuno' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
      {
        id: 'instr-3',
        text: { en: 'Give Vitamin D3 drops', es: 'Administre las gotas de Vitamina D3' },
        detail: { en: 'Give 1 mL (one full dropper) by mouth. Can mix with food or drink.', es: 'Administre 1 mL (un gotero lleno) por la boca. Se puede mezclar con comida o bebida.' },
        icon: 'droplet',
      },
    ],
    afternoon: [
      {
        id: 'instr-4',
        text: { en: 'Check blood sugar before lunch', es: 'Revise el azúcar en la sangre antes del almuerzo' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-5',
        text: { en: 'Give Humalog shot before lunch', es: 'Administre la inyección de Humalog antes del almuerzo' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
    ],
    evening: [
      {
        id: 'instr-6',
        text: { en: 'Check blood sugar before dinner', es: 'Revise el azúcar en la sangre antes de la cena' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-7',
        text: { en: 'Give Humalog shot before dinner', es: 'Administre la inyección de Humalog antes de la cena' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
    ],
    bedtime: [
      {
        id: 'instr-8',
        text: { en: 'Check blood sugar at bedtime', es: 'Revise el azúcar en la sangre a la hora de dormir' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-9',
        text: { en: 'Give Lantus shot at bedtime', es: 'Administre la inyección de Lantus a la hora de dormir' },
        detail: { en: 'Give the shot under the skin. Rotate injection sites each time to prevent lumps.', es: 'Administre la inyección bajo la piel. Rote los sitios de inyección cada vez para prevenir bultos.' },
        icon: 'syringe',
      },
    ],
  },

  /* ── Recovery Checklist ── */
  checklist: [
    { id: 'ck-1', text: { en: 'Check blood sugar before breakfast', es: 'Revise el azúcar antes del desayuno' }, recurring: true, done: false },
    { id: 'ck-2', text: { en: 'Give morning medications', es: 'Administre medicamentos de la mañana' }, recurring: true, done: false },
    { id: 'ck-3', text: { en: 'Check blood sugar before lunch', es: 'Revise el azúcar antes del almuerzo' }, recurring: true, done: false },
    { id: 'ck-4', text: { en: 'Give Humalog before lunch', es: 'Administre Humalog antes del almuerzo' }, recurring: true, done: false },
    { id: 'ck-5', text: { en: 'Check blood sugar before dinner', es: 'Revise el azúcar antes de la cena' }, recurring: true, done: false },
    { id: 'ck-6', text: { en: 'Give Humalog before dinner', es: 'Administre Humalog antes de la cena' }, recurring: true, done: false },
    { id: 'ck-7', text: { en: 'Check blood sugar at bedtime', es: 'Revise el azúcar a la hora de dormir' }, recurring: true, done: false },
    { id: 'ck-8', text: { en: 'Give Lantus shot at bedtime', es: 'Administre inyección de Lantus al acostarse' }, recurring: true, done: false },
    { id: 'ck-9', text: { en: 'Log all blood sugar readings', es: 'Registre todas las lecturas de azúcar' }, recurring: true, done: false },
    { id: 'ck-10', text: { en: 'Pick up Vitamin D3 from pharmacy', es: 'Recoja Vitamina D3 de la farmacia' }, recurring: false, done: false },
    { id: 'ck-11', text: { en: 'Set up blood sugar log book', es: 'Prepare el cuaderno de registro de azúcar' }, recurring: false, done: false },
    { id: 'ck-12', text: { en: 'Store insulin properly in fridge', es: 'Almacene la insulina correctamente en el refrigerador' }, recurring: false, done: false },
  ],

  /* ── Warning Signs (from DC pages 1 & 3) ── */
  warnings: {
    red: {
      label: { en: 'Call 911', es: 'Llame al 911' },
      items: [
        { text: { en: 'Child is unconscious or not waking up', es: 'El niño/a está inconsciente o no se despierta' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
        { text: { en: 'Child is having a seizure', es: 'El niño/a está teniendo una convulsión' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
        { text: { en: 'Child is confused and cannot drink', es: 'El niño/a está confundido/a y no puede beber' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
      ],
    },
    yellow: {
      label: { en: 'Call the doctor', es: 'Llame al médico' },
      items: [
        { text: { en: 'Blood sugar stays above 300', es: 'El azúcar en la sangre se mantiene por encima de 300' }, action: { en: 'Call Dr. Sellers or CHOC nurse line', es: 'Llame al Dr. Sellers o a la línea de enfermería de CHOC' } },
        { text: { en: 'Blood sugar drops below 70', es: 'El azúcar en la sangre baja de 70' }, action: { en: 'Give juice first, then call doctor', es: 'Dé jugo primero, luego llame al médico' } },
        { text: { en: 'Moderate or large ketones in urine', es: 'Cetonas moderadas o grandes en la orina' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Vomiting and cannot keep fluids down', es: 'Vomitando y no puede retener líquidos' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Fruity smell on breath', es: 'Olor a fruta en el aliento' }, action: { en: 'Check blood sugar and ketones, call doctor', es: 'Revise el azúcar y cetonas, llame al médico' } },
        { text: { en: 'Breathing very fast', es: 'Respirando muy rápido' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Very sleepy or hard to wake', es: 'Muy adormilado/a o difícil de despertar' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
      ],
    },
    green: {
      label: { en: 'Watch at home', es: 'Observe en casa' },
      items: [
        { text: { en: 'Shakiness, sweating, pale skin', es: 'Temblores, sudoración, piel pálida' }, action: { en: 'This may be low blood sugar. Give 4 oz juice, wait 15 min, recheck.', es: 'Esto puede ser azúcar baja. Dé 4 oz de jugo, espere 15 min, revise de nuevo.' } },
        { text: { en: 'Hungry, irritable, or confused', es: 'Hambriento/a, irritable o confundido/a' }, action: { en: 'Check blood sugar. If low, give juice and a snack.', es: 'Revise el azúcar. Si está baja, dé jugo y un refrigerio.' } },
        { text: { en: 'More thirsty or peeing more than usual', es: 'Más sediento/a u orinando más de lo normal' }, action: { en: 'This may be high blood sugar. Check and follow sliding scale.', es: 'Esto puede ser azúcar alta. Revise y siga la escala variable.' } },
        { text: { en: 'Tired, dizzy, or headache', es: 'Cansado/a, mareado/a o dolor de cabeza' }, action: { en: 'Check blood sugar. Give water. Rest. Recheck in 30 min.', es: 'Revise el azúcar. Dé agua. Descanse. Revise de nuevo en 30 min.' } },
      ],
    },
  },

  /* ── Low Blood Sugar Treatment Protocol (always visible in Meds tab) ── */
  lowBloodSugarSteps: [
    { en: 'Give 4 oz (half cup) of juice or 3-4 glucose tablets', es: 'Dé 4 oz (medio vaso) de jugo o 3-4 tabletas de glucosa' },
    { en: 'Wait 15 minutes', es: 'Espere 15 minutos' },
    { en: 'Check blood sugar again', es: 'Revise el azúcar en la sangre de nuevo' },
    { en: 'If still below 70, repeat step 1', es: 'Si todavía está por debajo de 70, repita el paso 1' },
  ],

  /* ── Sick Day Rules ── */
  sickDayRules: [
    { en: 'Never stop giving insulin, even if your child is not eating', es: 'Nunca deje de dar insulina, incluso si su hijo/a no está comiendo' },
    { en: 'Check blood sugar every 2 to 4 hours', es: 'Revise el azúcar en la sangre cada 2 a 4 horas' },
    { en: 'Check for ketones if blood sugar is over 250', es: 'Revise las cetonas si el azúcar está por encima de 250' },
    { en: 'Give extra water and clear fluids to prevent dehydration', es: 'Dé agua extra y líquidos claros para prevenir la deshidratación' },
  ],

  /* ── Appointments (from DC summary) ── */
  appointments: [
    {
      id: 'apt-1',
      date: '2026-04-22',
      time: '8:23 AM',
      type: { en: 'Endocrinology Follow-Up', es: 'Seguimiento de Endocrinología' },
      provider: 'Dr. Lester',
      location: 'CHOC Health Center - Garden Grove',
      address: '12555 Garden Grove Blvd, Garden Grove, CA 92843',
      bringItems: {
        en: ['Blood sugar log book', 'List of questions for the doctor', 'All insulin pens/vials'],
        es: ['Cuaderno de registro de azúcar', 'Lista de preguntas para el médico', 'Todas las plumas/frascos de insulina'],
      },
    },
    {
      id: 'apt-2',
      date: '2026-05-18',
      time: '8:23 AM',
      type: { en: 'Endocrinology Follow-Up', es: 'Seguimiento de Endocrinología' },
      provider: 'Dr. Wang',
      location: 'CHOC Health Center - Newport Beach',
      address: '500 Superior Ave, Newport Beach, CA 92663',
      bringItems: {
        en: ['Blood sugar log book', 'List of questions for the doctor'],
        es: ['Cuaderno de registro de azúcar', 'Lista de preguntas para el médico'],
      },
    },
  ],

  /* ── Social Needs Screening Questions ── */
  screening: [
    { id: 'scr-1', question: { en: 'Do you need help getting to doctor appointments?', es: '¿Necesita ayuda para llegar a las citas médicas?' }, category: 'transportation' },
    { id: 'scr-2', question: { en: 'Do you need help getting enough food for your family?', es: '¿Necesita ayuda para obtener suficiente comida para su familia?' }, category: 'food' },
    { id: 'scr-3', question: { en: 'Are you worried about your housing situation?', es: '¿Está preocupado/a por su situación de vivienda?' }, category: 'housing' },
    { id: 'scr-4', question: { en: 'Do you need help paying for medications or diabetes supplies?', es: '¿Necesita ayuda para pagar medicamentos o suministros para la diabetes?' }, category: 'financial' },
    { id: 'scr-5', question: { en: 'Do you need help communicating with your doctors in your language?', es: '¿Necesita ayuda para comunicarse con sus médicos en su idioma?' }, category: 'language' },
  ],

  /* ── Community Resources ── */
  resources: [
    {
      id: 'res-1',
      name: 'OCTA ACCESS',
      category: 'transportation',
      description: { en: 'Free and low-cost rides to medical appointments for eligible patients in Orange County', es: 'Transporte gratuito y de bajo costo a citas médicas para pacientes elegibles en el Condado de Orange' },
      phone: '(714) 560-5956',
      address: '550 S Main St, Orange, CA 92868',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-2',
      name: 'Medi-Cal Non-Emergency Transport',
      category: 'transportation',
      description: { en: 'Free rides to medical appointments for Medi-Cal members', es: 'Transporte gratuito a citas médicas para miembros de Medi-Cal' },
      phone: '(855) 575-0505',
      address: '',
      hours: { en: 'Mon-Fri 7am-7pm', es: 'Lun-Vie 7am-7pm' },
      languages: ['English', 'Spanish', 'Mandarin'],
    },
    {
      id: 'res-3',
      name: 'Second Harvest Food Bank',
      category: 'food',
      description: { en: 'Free food distribution for families in need. No ID required.', es: 'Distribución gratuita de alimentos para familias necesitadas. No se requiere identificación.' },
      phone: '(949) 653-2900',
      address: '8014 Marine Way, Irvine, CA 92618',
      hours: { en: 'Mon-Fri 8am-4:30pm', es: 'Lun-Vie 8am-4:30pm' },
      languages: ['English', 'Spanish', 'Vietnamese'],
    },
    {
      id: 'res-4',
      name: 'WIC (Women, Infants, Children)',
      category: 'food',
      description: { en: 'Free healthy food, nutrition help, and referrals for pregnant and postpartum women, infants, and children under 5', es: 'Alimentos saludables gratuitos, ayuda nutricional y referencias para mujeres embarazadas y posparto, bebés y niños menores de 5 años' },
      phone: '(714) 834-8200',
      address: '1725 W 17th St, Santa Ana, CA 92706',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish', 'Vietnamese', 'Mandarin'],
    },
    {
      id: 'res-5',
      name: 'OC Housing Authority',
      category: 'housing',
      description: { en: 'Affordable housing programs and rental assistance for low-income families', es: 'Programas de vivienda asequible y asistencia de alquiler para familias de bajos ingresos' },
      phone: '(714) 480-2700',
      address: '1770 N Broadway, Santa Ana, CA 92706',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-6',
      name: 'Lilly Insulin Value Program',
      category: 'financial',
      description: { en: 'Caps the cost of Humalog and other Lilly insulins at $35 per month per prescription', es: 'Limita el costo de Humalog y otras insulinas Lilly a $35 por mes por receta' },
      phone: '(800) 545-6962',
      address: '',
      hours: { en: 'Mon-Fri 8am-8pm EST', es: 'Lun-Vie 8am-8pm EST' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-7',
      name: 'JDRF Orange County',
      category: 'financial',
      description: { en: 'Type 1 Diabetes support, financial assistance for supplies, and family connections', es: 'Apoyo para Diabetes Tipo 1, asistencia financiera para suministros y conexiones familiares' },
      phone: '(949) 553-0363',
      address: '5 Hutton Centre Dr, Santa Ana, CA 92707',
      hours: { en: 'Mon-Fri 9am-5pm', es: 'Lun-Vie 9am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-8',
      name: 'OC Asian Pacific Community Health Center',
      category: 'language',
      description: { en: 'Health services with Mandarin, Cantonese, Vietnamese, and Korean interpreters. Can help with doctor visits.', es: 'Servicios de salud con intérpretes de mandarín, cantonés, vietnamita y coreano. Pueden ayudar con visitas al médico.' },
      phone: '(714) 636-1349',
      address: '12900 Garden Grove Blvd, Garden Grove, CA 92843',
      hours: { en: 'Mon-Fri 8:30am-5pm', es: 'Lun-Vie 8:30am-5pm' },
      languages: ['English', 'Mandarin', 'Cantonese', 'Vietnamese', 'Korean'],
    },
  ],

  /* ── UI Strings (bilingual) ── */
  strings: {
    en: {
      goodMorning: 'Good morning,',
      todayChecklist: "Today's checklist",
      done: 'done',
      nextMedication: 'Next medication',
      markAsTaken: 'Mark as taken',
      taken: 'Taken',
      warningSignsTitle: 'Warning signs',
      warningSignsSubtitle: 'When to get help',
      communityHelpTitle: 'Community help',
      communityHelpSubtitle: 'Food, rides, housing',
      carePlan: 'Care plan',
      medications: 'Meds',
      appointments: 'Appts',
      home: 'Home',
      dischargeSummary: 'Discharge summary',
      careInstructions: 'Care instructions',
      recoveryChecklist: 'Recovery checklist',
      warningSigns: 'Warning signs',
      sickDayRules: 'Sick day rules',
      call911: 'Call 911',
      callDoctor: 'Call the doctor',
      watchAtHome: 'Watch at home',
      lowBloodSugar: 'Low blood sugar? Do this:',
      pharmacyInfo: 'Pharmacy info',
      refillsLeft: 'refills left',
      callPharmacy: 'Call pharmacy',
      slidingScaleNote: 'Dose varies by blood sugar reading. Check your sliding scale chart.',
      getARide: 'Get a ride',
      addToCalendar: 'Add to calendar',
      whatToBring: 'What to bring',
      callToSchedule: 'Call to schedule',
      needsScreening: 'What help do you need?',
      yes: 'Yes',
      no: 'No',
      showResources: 'Show my resources',
      startOver: 'Start over',
      callNow: 'Call now',
      getDirections: 'Get directions',
      hoursLabel: 'Hours',
      languagesLabel: 'Languages',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      bedtime: 'Bedtime',
      daily: 'Daily',
      oneTime: 'One-time',
      supplementalResources: 'More information',
      medSafety: 'Medication safety',
      comfortTips: 'Comfort and pain tips',
      hospitalPortal: 'CHOC medical records',
      nurseLine: '24/7 Nurse line',
      back: 'Back',
    },
    es: {
      goodMorning: 'Buenos días,',
      todayChecklist: 'Lista de hoy',
      done: 'hechas',
      nextMedication: 'Próximo medicamento',
      markAsTaken: 'Marcar como tomado',
      taken: 'Tomado',
      warningSignsTitle: 'Señales de alerta',
      warningSignsSubtitle: 'Cuándo buscar ayuda',
      communityHelpTitle: 'Ayuda comunitaria',
      communityHelpSubtitle: 'Comida, transporte, vivienda',
      carePlan: 'Plan de cuidado',
      medications: 'Medicinas',
      appointments: 'Citas',
      home: 'Inicio',
      dischargeSummary: 'Resumen del alta',
      careInstructions: 'Instrucciones de cuidado',
      recoveryChecklist: 'Lista de recuperación',
      warningSigns: 'Señales de alerta',
      sickDayRules: 'Reglas para días de enfermedad',
      call911: 'Llame al 911',
      callDoctor: 'Llame al médico',
      watchAtHome: 'Observe en casa',
      lowBloodSugar: '¿Azúcar baja? Haga esto:',
      pharmacyInfo: 'Información de farmacia',
      refillsLeft: 'recargas restantes',
      callPharmacy: 'Llamar a la farmacia',
      slidingScaleNote: 'La dosis varía según la lectura de azúcar. Revise su tabla de escala variable.',
      getARide: 'Conseguir transporte',
      addToCalendar: 'Agregar al calendario',
      whatToBring: 'Qué llevar',
      callToSchedule: 'Llamar para programar',
      needsScreening: '¿Qué ayuda necesita?',
      yes: 'Sí',
      no: 'No',
      showResources: 'Mostrar mis recursos',
      startOver: 'Empezar de nuevo',
      callNow: 'Llamar ahora',
      getDirections: 'Cómo llegar',
      hoursLabel: 'Horario',
      languagesLabel: 'Idiomas',
      morning: 'Mañana',
      afternoon: 'Tarde',
      evening: 'Noche',
      bedtime: 'Hora de dormir',
      daily: 'Diario',
      oneTime: 'Una vez',
      supplementalResources: 'Más información',
      medSafety: 'Seguridad de medicamentos',
      comfortTips: 'Consejos de comodidad y dolor',
      hospitalPortal: 'Registros médicos de CHOC',
      nurseLine: 'Línea de enfermería 24/7',
      back: 'Volver',
    },
  },
};
