/* Care to Home Companion - Sample Data from CHOC DC Summary (LL #22: Build Fallback Data) */
/* All data structured as single source of truth (LL #4: One File Per Job) */

const DATA = {

  /* ── Patient Info ── */
  patient: {
    name: { en: 'Amber Rhodes', es: 'Amber Rhodes' },
    age: '2 years old',
    mrn: '768970',
    weight: '13.2 kg',
    allergies: { en: 'None known', es: 'Ninguna conocida' },
    preferredLanguage: 'Mandarin',
    admissionDate: '2026-03-25',
    dischargeDate: '2026-04-01',
    diagnosis: {
      en: 'Type 1 Diabetes - New Onset',
      es: 'Diabetes Tipo 1 - Nuevo Diagnóstico'
    },
    diagnosisPlain: {
      en: 'Your child was diagnosed with Type 1 Diabetes. This means her body can no longer make insulin on its own. She will need insulin every day.',
      es: 'Su hijo/a fue diagnosticado/a con Diabetes Tipo 1. Esto significa que su cuerpo ya no puede producir insulina por sí solo. Necesitará insulina todos los días.'
    },
    condition: { en: 'Good', es: 'Buena' },
    pcp: 'Dr. Sellers',
    consultingPhysicians: ['Dr. Flores, MD'],
    dischargeAuth: 'Dr. Miles, MD',
    diet: {
      en: 'Regular, Age Appropriate',
      es: 'Regular, Apropiada para su Edad'
    },
    diagnosisDetail: {
      en: 'Type 1 Diabetes is an autoimmune condition where the immune system attacks the insulin-producing cells in the pancreas. Unlike Type 2 Diabetes, it is not caused by diet or lifestyle. Your child will need insulin for the rest of her life. With proper management — checking blood sugar, giving insulin, and following a healthy diet — children with Type 1 Diabetes can live full, active lives. The care team at CHOC will work with you closely over the coming months to adjust doses and build your confidence.',
      es: 'La Diabetes Tipo 1 es una condición autoinmune donde el sistema inmunológico ataca las células productoras de insulina en el páncreas. A diferencia de la Diabetes Tipo 2, no es causada por la dieta o el estilo de vida. Su hijo/a necesitará insulina por el resto de su vida. Con un manejo adecuado — revisando el azúcar en la sangre, administrando insulina y siguiendo una dieta saludable — los niños con Diabetes Tipo 1 pueden vivir vidas plenas y activas. El equipo de atención de CHOC trabajará con usted de cerca durante los próximos meses para ajustar las dosis y aumentar su confianza.'
    },
  },

  /* ── Medications ── */
  medications: [
    {
      id: 'lantus',
      name: 'Insulin glargine (Lantus)',
      namePlain: { en: 'Lantus', es: 'Lantus' },
      dose: '100 units/mL',
      dosePlain: { en: 'As directed by doctor', es: 'Según las indicaciones del médico' },
      route: { en: 'Shot under the skin', es: 'Inyección bajo la piel' },
      frequency: { en: 'Once daily at bedtime', es: 'Una vez al día a la hora de dormir' },
      timeBlock: 'bedtime',
      purpose: {
        en: 'Long-acting insulin that works all day and night to keep blood sugar steady',
        es: 'Insulina de acción prolongada que trabaja todo el día y la noche para mantener el azúcar en la sangre estable'
      },
      icon: 'syringe',
      refills: 2,
      pharmacy: 'Rite Aid Pharmacy #4532',
    },
    {
      id: 'humalog',
      name: 'Insulin lispro (Humalog)',
      namePlain: { en: 'Humalog', es: 'Humalog' },
      dose: '100 units/mL',
      dosePlain: { en: 'Per sliding scale', es: 'Según escala variable' },
      route: { en: 'Shot under the skin', es: 'Inyección bajo la piel' },
      frequency: { en: 'Before each meal', es: 'Antes de cada comida' },
      timeBlock: 'meals',
      purpose: {
        en: 'Fast-acting insulin given before meals to control blood sugar from food',
        es: 'Insulina de acción rápida administrada antes de las comidas para controlar el azúcar en la sangre de los alimentos'
      },
      icon: 'syringe',
      refills: 2,
      pharmacy: 'Rite Aid Pharmacy #4532',
      slidingScale: true,
    },
    {
      id: 'vitamind',
      name: 'Vitamin D3 400 IU drops',
      namePlain: { en: 'Vitamin D3 drops', es: 'Gotas de Vitamina D3' },
      dose: '400 IU',
      dosePlain: { en: '1 mL (one dropper full)', es: '1 mL (un gotero lleno)' },
      route: { en: 'By mouth', es: 'Por la boca' },
      frequency: { en: 'Once daily', es: 'Una vez al día' },
      timeBlock: 'morning',
      purpose: {
        en: 'Helps keep bones strong and supports the immune system',
        es: 'Ayuda a mantener los huesos fuertes y apoya el sistema inmunológico'
      },
      icon: 'droplet',
      refills: 0,
      pharmacy: 'Rite Aid Pharmacy #4532',
    },
  ],

  /* ── Care Instructions (by time of day) ── */
  instructions: {
    morning: [
      {
        id: 'instr-1',
        text: { en: 'Check blood sugar before breakfast', es: 'Revise el azúcar en la sangre antes del desayuno' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-2',
        text: { en: 'Give Humalog shot before breakfast', es: 'Administre la inyección de Humalog antes del desayuno' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
      {
        id: 'instr-3',
        text: { en: 'Give Vitamin D3 drops', es: 'Administre las gotas de Vitamina D3' },
        detail: { en: 'Give 1 mL (one full dropper) by mouth. Can mix with food or drink.', es: 'Administre 1 mL (un gotero lleno) por la boca. Se puede mezclar con comida o bebida.' },
        icon: 'droplet',
      },
    ],
    afternoon: [
      {
        id: 'instr-4',
        text: { en: 'Check blood sugar before lunch', es: 'Revise el azúcar en la sangre antes del almuerzo' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-5',
        text: { en: 'Give Humalog shot before lunch', es: 'Administre la inyección de Humalog antes del almuerzo' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
    ],
    evening: [
      {
        id: 'instr-6',
        text: { en: 'Check blood sugar before dinner', es: 'Revise el azúcar en la sangre antes de la cena' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-7',
        text: { en: 'Give Humalog shot before dinner', es: 'Administre la inyección de Humalog antes de la cena' },
        detail: { en: 'Check the sliding scale chart for the right dose based on blood sugar reading.', es: 'Revise la tabla de escala variable para la dosis correcta según la lectura de azúcar en la sangre.' },
        icon: 'syringe',
      },
    ],
    bedtime: [
      {
        id: 'instr-8',
        text: { en: 'Check blood sugar at bedtime', es: 'Revise el azúcar en la sangre a la hora de dormir' },
        detail: { en: 'Use the glucose meter. Write the number in the log book.', es: 'Use el medidor de glucosa. Escriba el número en el cuaderno de registro.' },
        icon: 'droplet',
      },
      {
        id: 'instr-9',
        text: { en: 'Give Lantus shot at bedtime', es: 'Administre la inyección de Lantus a la hora de dormir' },
        detail: { en: 'Give the shot under the skin. Rotate injection sites each time to prevent lumps.', es: 'Administre la inyección bajo la piel. Rote los sitios de inyección cada vez para prevenir bultos.' },
        icon: 'syringe',
      },
    ],
  },

  /* ── Recovery Checklist ── */
  checklist: [
    { id: 'ck-1', text: { en: 'Check blood sugar before breakfast', es: 'Revise el azúcar antes del desayuno' }, recurring: true, done: false },
    { id: 'ck-2', text: { en: 'Give morning medications', es: 'Administre medicamentos de la mañana' }, recurring: true, done: false },
    { id: 'ck-3', text: { en: 'Check blood sugar before lunch', es: 'Revise el azúcar antes del almuerzo' }, recurring: true, done: false },
    { id: 'ck-4', text: { en: 'Give Humalog before lunch', es: 'Administre Humalog antes del almuerzo' }, recurring: true, done: false },
    { id: 'ck-5', text: { en: 'Check blood sugar before dinner', es: 'Revise el azúcar antes de la cena' }, recurring: true, done: false },
    { id: 'ck-6', text: { en: 'Give Humalog before dinner', es: 'Administre Humalog antes de la cena' }, recurring: true, done: false },
    { id: 'ck-7', text: { en: 'Check blood sugar at bedtime', es: 'Revise el azúcar a la hora de dormir' }, recurring: true, done: false },
    { id: 'ck-8', text: { en: 'Give Lantus shot at bedtime', es: 'Administre inyección de Lantus al acostarse' }, recurring: true, done: false },
    { id: 'ck-9', text: { en: 'Log all blood sugar readings', es: 'Registre todas las lecturas de azúcar' }, recurring: true, done: false },
    { id: 'ck-10', text: { en: 'Pick up Vitamin D3 from pharmacy', es: 'Recoja Vitamina D3 de la farmacia' }, recurring: false, done: false },
    { id: 'ck-11', text: { en: 'Set up blood sugar log book', es: 'Prepare el cuaderno de registro de azúcar' }, recurring: false, done: false },
    { id: 'ck-12', text: { en: 'Store insulin properly in fridge', es: 'Almacene la insulina correctamente en el refrigerador' }, recurring: false, done: false },
  ],

  /* ── Sliding Scale Chart (Humalog dosing by blood sugar range) ── */
  slidingScale: {
    title: { en: 'Humalog Sliding Scale', es: 'Escala Variable de Humalog' },
    subtitle: { en: 'Check blood sugar before meals. Give this dose of Humalog based on the reading:', es: 'Revise el azúcar antes de las comidas. Administre esta dosis de Humalog según la lectura:' },
    rows: [
      { range: { en: 'Below 70', es: 'Menos de 70' }, dose: { en: 'Do NOT give — treat low blood sugar first', es: 'NO administre — trate el azúcar baja primero' }, level: 'low' },
      { range: { en: '70 – 150', es: '70 – 150' }, dose: { en: '0.5 units', es: '0.5 unidades' }, level: 'normal' },
      { range: { en: '151 – 200', es: '151 – 200' }, dose: { en: '1 unit', es: '1 unidad' }, level: 'normal' },
      { range: { en: '201 – 250', es: '201 – 250' }, dose: { en: '1.5 units', es: '1.5 unidades' }, level: 'watch' },
      { range: { en: '251 – 300', es: '251 – 300' }, dose: { en: '2 units + check ketones', es: '2 unidades + revise cetones' }, level: 'watch' },
      { range: { en: 'Above 300', es: 'Más de 300' }, dose: { en: '2 units + call doctor', es: '2 unidades + llame al médico' }, level: 'high' },
    ],
  },

  /* ── Checklist-to-Medication Mapping ── */
  checklistMedMap: {
    'ck-2': 'humalog',
    'ck-4': 'humalog',
    'ck-6': 'humalog',
    'ck-8': 'lantus',
  },

  /* ── Warning Signs (from DC pages 1 & 3) ── */
  warnings: {
    red: {
      label: { en: 'Call 911', es: 'Llame al 911' },
      items: [
        { text: { en: 'Child is unconscious or not waking up', es: 'El niño/a está inconsciente o no se despierta' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
        { text: { en: 'Child is having a seizure', es: 'El niño/a está teniendo una convulsión' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
        { text: { en: 'Child is confused and cannot drink', es: 'El niño/a está confundido/a y no puede beber' }, action: { en: 'Call 911 right away', es: 'Llame al 911 de inmediato' } },
      ],
    },
    yellow: {
      label: { en: 'Call the doctor', es: 'Llame al médico' },
      items: [
        { text: { en: 'Blood sugar stays above 300', es: 'El azúcar en la sangre se mantiene por encima de 300' }, action: { en: 'Call Dr. Sellers or CHOC nurse line', es: 'Llame al Dr. Sellers o a la línea de enfermería de CHOC' } },
        { text: { en: 'Blood sugar drops below 70', es: 'El azúcar en la sangre baja de 70' }, action: { en: 'Give juice first, then call doctor', es: 'Dé jugo primero, luego llame al médico' } },
        { text: { en: 'Moderate or large ketones in urine', es: 'Cetonas moderadas o grandes en la orina' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Vomiting and cannot keep fluids down', es: 'Vomitando y no puede retener líquidos' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Fruity smell on breath', es: 'Olor a fruta en el aliento' }, action: { en: 'Check blood sugar and ketones, call doctor', es: 'Revise el azúcar y cetonas, llame al médico' } },
        { text: { en: 'Breathing very fast', es: 'Respirando muy rápido' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
        { text: { en: 'Very sleepy or hard to wake', es: 'Muy adormilado/a o difícil de despertar' }, action: { en: 'Call the doctor right away', es: 'Llame al médico de inmediato' } },
      ],
    },
    green: {
      label: { en: 'Watch at home', es: 'Observe en casa' },
      items: [
        { text: { en: 'Shakiness, sweating, pale skin', es: 'Temblores, sudoración, piel pálida' }, action: { en: 'This may be low blood sugar. Give 4 oz juice, wait 15 min, recheck.', es: 'Esto puede ser azúcar baja. Dé 4 oz de jugo, espere 15 min, revise de nuevo.' } },
        { text: { en: 'Hungry, irritable, or confused', es: 'Hambriento/a, irritable o confundido/a' }, action: { en: 'Check blood sugar. If low, give juice and a snack.', es: 'Revise el azúcar. Si está baja, dé jugo y un refrigerio.' } },
        { text: { en: 'More thirsty or peeing more than usual', es: 'Más sediento/a u orinando más de lo normal' }, action: { en: 'This may be high blood sugar. Check and follow sliding scale.', es: 'Esto puede ser azúcar alta. Revise y siga la escala variable.' } },
        { text: { en: 'Tired, dizzy, or headache', es: 'Cansado/a, mareado/a o dolor de cabeza' }, action: { en: 'Check blood sugar. Give water. Rest. Recheck in 30 min.', es: 'Revise el azúcar. Dé agua. Descanse. Revise de nuevo en 30 min.' } },
      ],
    },
  },

  /* ── Low Blood Sugar Treatment Protocol (always visible in Meds tab) ── */
  lowBloodSugarSteps: [
    { en: 'Give 4 oz (half cup) of juice or 3-4 glucose tablets', es: 'Dé 4 oz (medio vaso) de jugo o 3-4 tabletas de glucosa' },
    { en: 'Wait 15 minutes', es: 'Espere 15 minutos' },
    { en: 'Check blood sugar again', es: 'Revise el azúcar en la sangre de nuevo' },
    { en: 'If still below 70, repeat step 1', es: 'Si todavía está por debajo de 70, repita el paso 1' },
  ],

  /* ── Sick Day Rules ── */
  sickDayRules: [
    { en: 'Never stop giving insulin, even if your child is not eating', es: 'Nunca deje de dar insulina, incluso si su hijo/a no está comiendo' },
    { en: 'Check blood sugar every 2 to 4 hours', es: 'Revise el azúcar en la sangre cada 2 a 4 horas' },
    { en: 'Check for ketones if blood sugar is over 250', es: 'Revise las cetonas si el azúcar está por encima de 250' },
    { en: 'Give extra water and clear fluids to prevent dehydration', es: 'Dé agua extra y líquidos claros para prevenir la deshidratación' },
  ],

  /* ── Appointments (from DC summary) ── */
  appointments: [
    {
      id: 'apt-1',
      date: '2026-04-22',
      time: '8:23 AM',
      type: { en: 'Endocrinology Follow-Up', es: 'Seguimiento de Endocrinología' },
      provider: 'Dr. Lester',
      location: 'CHOC Health Center - Garden Grove',
      address: '12555 Garden Grove Blvd, Garden Grove, CA 92843',
      bringItems: {
        en: ['Blood sugar log book', 'List of questions for the doctor', 'All insulin pens/vials'],
        es: ['Cuaderno de registro de azúcar', 'Lista de preguntas para el médico', 'Todas las plumas/frascos de insulina'],
      },
    },
    {
      id: 'apt-2',
      date: '2026-05-18',
      time: '8:23 AM',
      type: { en: 'Endocrinology Follow-Up', es: 'Seguimiento de Endocrinología' },
      provider: 'Dr. Wang',
      location: 'CHOC Health Center - Newport Beach',
      address: '500 Superior Ave, Newport Beach, CA 92663',
      bringItems: {
        en: ['Blood sugar log book', 'List of questions for the doctor'],
        es: ['Cuaderno de registro de azúcar', 'Lista de preguntas para el médico'],
      },
    },
  ],

  /* ── Social Needs Screening Questions ── */
  screening: [
    { id: 'scr-1', question: { en: 'Do you need help getting to doctor appointments?', es: '¿Necesita ayuda para llegar a las citas médicas?' }, category: 'transportation' },
    { id: 'scr-2', question: { en: 'Do you need help getting enough food for your family?', es: '¿Necesita ayuda para obtener suficiente comida para su familia?' }, category: 'food' },
    { id: 'scr-3', question: { en: 'Are you worried about your housing situation?', es: '¿Está preocupado/a por su situación de vivienda?' }, category: 'housing' },
    { id: 'scr-4', question: { en: 'Do you need help paying for medications or diabetes supplies?', es: '¿Necesita ayuda para pagar medicamentos o suministros para la diabetes?' }, category: 'financial' },
    { id: 'scr-5', question: { en: 'Do you need help communicating with your doctors in your language?', es: '¿Necesita ayuda para comunicarse con sus médicos en su idioma?' }, category: 'language' },
  ],

  /* ── Community Resources ── */
  resources: [
    {
      id: 'res-1',
      name: 'OCTA ACCESS',
      category: 'transportation',
      description: { en: 'Free and low-cost rides to medical appointments for eligible patients in Orange County', es: 'Transporte gratuito y de bajo costo a citas médicas para pacientes elegibles en el Condado de Orange' },
      phone: '(714) 560-5956',
      address: '550 S Main St, Orange, CA 92868',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-2',
      name: 'Medi-Cal Non-Emergency Transport',
      category: 'transportation',
      description: { en: 'Free rides to medical appointments for Medi-Cal members', es: 'Transporte gratuito a citas médicas para miembros de Medi-Cal' },
      phone: '(855) 575-0505',
      address: '',
      hours: { en: 'Mon-Fri 7am-7pm', es: 'Lun-Vie 7am-7pm' },
      languages: ['English', 'Spanish', 'Mandarin'],
    },
    {
      id: 'res-3',
      name: 'Second Harvest Food Bank',
      category: 'food',
      description: { en: 'Free food distribution for families in need. No ID required.', es: 'Distribución gratuita de alimentos para familias necesitadas. No se requiere identificación.' },
      phone: '(949) 653-2900',
      address: '8014 Marine Way, Irvine, CA 92618',
      hours: { en: 'Mon-Fri 8am-4:30pm', es: 'Lun-Vie 8am-4:30pm' },
      languages: ['English', 'Spanish', 'Vietnamese'],
    },
    {
      id: 'res-4',
      name: 'WIC (Women, Infants, Children)',
      category: 'food',
      description: { en: 'Free healthy food, nutrition help, and referrals for pregnant and postpartum women, infants, and children under 5', es: 'Alimentos saludables gratuitos, ayuda nutricional y referencias para mujeres embarazadas y posparto, bebés y niños menores de 5 años' },
      phone: '(714) 834-8200',
      address: '1725 W 17th St, Santa Ana, CA 92706',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish', 'Vietnamese', 'Mandarin'],
    },
    {
      id: 'res-5',
      name: 'OC Housing Authority',
      category: 'housing',
      description: { en: 'Affordable housing programs and rental assistance for low-income families', es: 'Programas de vivienda asequible y asistencia de alquiler para familias de bajos ingresos' },
      phone: '(714) 480-2700',
      address: '1770 N Broadway, Santa Ana, CA 92706',
      hours: { en: 'Mon-Fri 8am-5pm', es: 'Lun-Vie 8am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-6',
      name: 'Lilly Insulin Value Program',
      category: 'financial',
      description: { en: 'Caps the cost of Humalog and other Lilly insulins at $35 per month per prescription', es: 'Limita el costo de Humalog y otras insulinas Lilly a $35 por mes por receta' },
      phone: '(800) 545-6962',
      address: '',
      hours: { en: 'Mon-Fri 8am-8pm EST', es: 'Lun-Vie 8am-8pm EST' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-7',
      name: 'JDRF Orange County',
      category: 'financial',
      description: { en: 'Type 1 Diabetes support, financial assistance for supplies, and family connections', es: 'Apoyo para Diabetes Tipo 1, asistencia financiera para suministros y conexiones familiares' },
      phone: '(949) 553-0363',
      address: '5 Hutton Centre Dr, Santa Ana, CA 92707',
      hours: { en: 'Mon-Fri 9am-5pm', es: 'Lun-Vie 9am-5pm' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'res-8',
      name: 'OC Asian Pacific Community Health Center',
      category: 'language',
      description: { en: 'Health services with Mandarin, Cantonese, Vietnamese, and Korean interpreters. Can help with doctor visits.', es: 'Servicios de salud con intérpretes de mandarín, cantonés, vietnamita y coreano. Pueden ayudar con visitas al médico.' },
      phone: '(714) 636-1349',
      address: '12900 Garden Grove Blvd, Garden Grove, CA 92843',
      hours: { en: 'Mon-Fri 8:30am-5pm', es: 'Lun-Vie 8:30am-5pm' },
      languages: ['English', 'Mandarin', 'Cantonese', 'Vietnamese', 'Korean'],
    },
  ],

  /* ── UI Strings (bilingual) ── */
  strings: {
    en: {
      goodMorning: 'Good morning,',
      todayChecklist: "Today's checklist",
      done: 'done',
      nextMedication: 'Next medication',
      markAsTaken: 'Mark as taken',
      taken: 'Taken',
      warningSignsTitle: 'Warning signs',
      warningSignsSubtitle: 'When to get help',
      communityHelpTitle: 'Community help',
      communityHelpSubtitle: 'Food, rides, housing',
      carePlan: 'Care plan',
      medications: 'Meds',
      appointments: 'Appts',
      home: 'Home',
      dischargeSummary: 'Discharge summary',
      careInstructions: 'Care instructions',
      recoveryChecklist: 'Recovery checklist',
      warningSigns: 'Warning signs',
      sickDayRules: 'Sick day rules',
      call911: 'Call 911',
      callDoctor: 'Call the doctor',
      watchAtHome: 'Watch at home',
      lowBloodSugar: 'Low blood sugar? Do this:',
      pharmacyInfo: 'Pharmacy info',
      refillsLeft: 'refills left',
      callPharmacy: 'Call pharmacy',
      slidingScaleNote: 'Dose varies by blood sugar reading. Check your sliding scale chart.',
      getARide: 'Get a ride',
      addToCalendar: 'Add to calendar',
      whatToBring: 'What to bring',
      callToSchedule: 'Call to schedule',
      needsScreening: 'What help do you need?',
      yes: 'Yes',
      no: 'No',
      showResources: 'Show my resources',
      startOver: 'Start over',
      callNow: 'Call now',
      getDirections: 'Get directions',
      hoursLabel: 'Hours',
      languagesLabel: 'Languages',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      bedtime: 'Bedtime',
      daily: 'Daily',
      oneTime: 'One-time',
      supplementalResources: 'More information',
      medSafety: 'Medication safety',
      comfortTips: 'Comfort and pain tips',
      hospitalPortal: 'CHOC medical records',
      nurseLine: '24/7 Nurse line',
      back: 'Back',
      faq: 'FAQ',
      socialResources: 'Social',
      faqTitle: 'Frequently Asked Questions',
      socialTitle: 'Social Services & Support',
      chatGreeting: 'Hi! I can help you find info about medications, appointments, warning signs, and more. What do you need help with?',
      chatNoResults: 'I couldn\'t find specific info on that. Try asking about medications, appointments, warning signs, blood sugar, or diet. You can also call the 24/7 Nurse Line for help.',
      askPlaceholder: 'Ask about meds, appointments...',
      chatAssistant: 'Care Assistant',
      socialEligibility: 'Eligibility',
      socialApply: 'How to apply',
      socialWebsite: 'Visit website',
      moreInfo: 'More about this diagnosis',
      lessInfo: 'Show less',
      slidingScaleTitle: 'Humalog Sliding Scale',
      bloodSugarRange: 'Blood sugar (mg/dL)',
      humalogDose: 'Humalog dose',
      printForDoctor: 'Print for doctor visit',
      printTitle: 'Doctor Visit Summary',
      printPatientInfo: 'Patient Information',
      printAge: 'Age',
      printMRN: 'MRN',
      printDiagnosis: 'Diagnosis',
      printAllergies: 'Allergies',
      printDischargeDate: 'Discharge date',
      printPCP: 'Primary care physician',
      printCurrentMeds: 'Current Medications',
      printMedName: 'Medication',
      printDose: 'Dose',
      printFrequency: 'Frequency',
      printRoute: 'Route',
      printBloodSugarLog: 'Blood Sugar Log (Last 7 Days)',
      printDate: 'Date',
      printBreakfast: 'Before breakfast',
      printLunch: 'Before lunch',
      printDinner: 'Before dinner',
      printBedtime: 'Bedtime',
      printNotes: 'Notes',
      printUpcoming: 'Upcoming Appointments',
      printWarningSigns: 'Warning Signs Observed',
      printNoneReported: 'None reported',
      printQuestions: 'Questions & Concerns for Doctor',
      printWriteHere: '(Write your questions here)',
      printFooter: 'Generated from Care to Home Companion',
      printSlidingScale: 'Current Sliding Scale',
      printCaregiverNotes: 'Caregiver Notes',
    },
    es: {
      goodMorning: 'Buenos días,',
      todayChecklist: 'Lista de hoy',
      done: 'hechas',
      nextMedication: 'Próximo medicamento',
      markAsTaken: 'Marcar como tomado',
      taken: 'Tomado',
      warningSignsTitle: 'Señales de alerta',
      warningSignsSubtitle: 'Cuándo buscar ayuda',
      communityHelpTitle: 'Ayuda comunitaria',
      communityHelpSubtitle: 'Comida, transporte, vivienda',
      carePlan: 'Plan de cuidado',
      medications: 'Medicinas',
      appointments: 'Citas',
      home: 'Inicio',
      dischargeSummary: 'Resumen del alta',
      careInstructions: 'Instrucciones de cuidado',
      recoveryChecklist: 'Lista de recuperación',
      warningSigns: 'Señales de alerta',
      sickDayRules: 'Reglas para días de enfermedad',
      call911: 'Llame al 911',
      callDoctor: 'Llame al médico',
      watchAtHome: 'Observe en casa',
      lowBloodSugar: '¿Azúcar baja? Haga esto:',
      pharmacyInfo: 'Información de farmacia',
      refillsLeft: 'recargas restantes',
      callPharmacy: 'Llamar a la farmacia',
      slidingScaleNote: 'La dosis varía según la lectura de azúcar. Revise su tabla de escala variable.',
      getARide: 'Conseguir transporte',
      addToCalendar: 'Agregar al calendario',
      whatToBring: 'Qué llevar',
      callToSchedule: 'Llamar para programar',
      needsScreening: '¿Qué ayuda necesita?',
      yes: 'Sí',
      no: 'No',
      showResources: 'Mostrar mis recursos',
      startOver: 'Empezar de nuevo',
      callNow: 'Llamar ahora',
      getDirections: 'Cómo llegar',
      hoursLabel: 'Horario',
      languagesLabel: 'Idiomas',
      morning: 'Mañana',
      afternoon: 'Tarde',
      evening: 'Noche',
      bedtime: 'Hora de dormir',
      daily: 'Diario',
      oneTime: 'Una vez',
      supplementalResources: 'Más información',
      medSafety: 'Seguridad de medicamentos',
      comfortTips: 'Consejos de comodidad y dolor',
      hospitalPortal: 'Registros médicos de CHOC',
      nurseLine: 'Línea de enfermería 24/7',
      back: 'Volver',
      faq: 'Preguntas',
      socialResources: 'Social',
      faqTitle: 'Preguntas frecuentes',
      socialTitle: 'Servicios sociales y apoyo',
      chatGreeting: '¡Hola! Puedo ayudarte a encontrar información sobre medicamentos, citas, señales de alerta y más. ¿En qué necesitas ayuda?',
      chatNoResults: 'No encontré información específica sobre eso. Intenta preguntar sobre medicamentos, citas, señales de alerta, azúcar en sangre o dieta. También puedes llamar a la Línea de Enfermería 24/7.',
      askPlaceholder: 'Pregunta sobre medicinas, citas...',
      chatAssistant: 'Asistente de Cuidado',
      socialEligibility: 'Elegibilidad',
      socialApply: 'Cómo aplicar',
      socialWebsite: 'Visitar sitio web',
      moreInfo: 'Más sobre este diagnóstico',
      lessInfo: 'Mostrar menos',
      slidingScaleTitle: 'Escala Variable de Humalog',
      bloodSugarRange: 'Azúcar en sangre (mg/dL)',
      humalogDose: 'Dosis de Humalog',
      printForDoctor: 'Imprimir para visita médica',
      printTitle: 'Resumen para Visita Médica',
      printPatientInfo: 'Información del Paciente',
      printAge: 'Edad',
      printMRN: 'MRN',
      printDiagnosis: 'Diagnóstico',
      printAllergies: 'Alergias',
      printDischargeDate: 'Fecha de alta',
      printPCP: 'Médico de cabecera',
      printCurrentMeds: 'Medicamentos Actuales',
      printMedName: 'Medicamento',
      printDose: 'Dosis',
      printFrequency: 'Frecuencia',
      printRoute: 'Vía',
      printBloodSugarLog: 'Registro de Azúcar en Sangre (Últimos 7 Días)',
      printDate: 'Fecha',
      printBreakfast: 'Antes del desayuno',
      printLunch: 'Antes del almuerzo',
      printDinner: 'Antes de la cena',
      printBedtime: 'Hora de dormir',
      printNotes: 'Notas',
      printUpcoming: 'Próximas Citas',
      printWarningSigns: 'Señales de Alerta Observadas',
      printNoneReported: 'Ninguna reportada',
      printQuestions: 'Preguntas e Inquietudes para el Médico',
      printWriteHere: '(Escriba sus preguntas aquí)',
      printFooter: 'Generado desde Care to Home Companion',
      printSlidingScale: 'Escala Variable Actual',
      printCaregiverNotes: 'Notas del Cuidador',
    },
  },

  /* ── FAQ ── */
  faq: [
    {
      id: 'faq-1',
      question: { en: 'When should I give insulin?', es: '¿Cuándo debo dar insulina?' },
      answer: { en: 'Lantus (long-acting) is given once daily at bedtime (9:00 PM). Humalog (fast-acting) is given before each meal based on blood sugar readings using the sliding scale chart your care team provided.', es: 'Lantus (acción prolongada) se da una vez al día a la hora de dormir (9:00 PM). Humalog (acción rápida) se da antes de cada comida según las lecturas de azúcar en sangre usando la tabla de escala variable que su equipo médico proporcionó.' },
    },
    {
      id: 'faq-2',
      question: { en: 'What is a normal blood sugar range?', es: '¿Cuál es el rango normal de azúcar en sangre?' },
      answer: { en: 'For your child, target blood sugar is between 70-180 mg/dL. Below 70 is low (follow the low blood sugar protocol). Above 250 requires checking for ketones. Above 300 — call the doctor immediately.', es: 'Para su hijo/a, el azúcar objetivo es entre 70-180 mg/dL. Menos de 70 es bajo (siga el protocolo de azúcar baja). Más de 250 requiere revisar cetonas. Más de 300 — llame al médico de inmediato.' },
    },
    {
      id: 'faq-3',
      question: { en: 'What do I do if my child won\'t eat?', es: '¿Qué hago si mi hijo/a no quiere comer?' },
      answer: { en: 'Never skip Lantus (long-acting insulin). If your child won\'t eat a full meal, give Humalog after the meal based on what they actually ate. Offer small, frequent snacks. Check blood sugar more often. Call the nurse line if they refuse food for more than one meal.', es: 'Nunca omita Lantus (insulina de acción prolongada). Si su hijo/a no come toda la comida, dé Humalog después de la comida según lo que realmente comió. Ofrezca bocadillos pequeños y frecuentes. Revise el azúcar más seguido. Llame a la línea de enfermería si rechaza comida por más de una comida.' },
    },
    {
      id: 'faq-4',
      question: { en: 'How do I store insulin?', es: '¿Cómo almaceno la insulina?' },
      answer: { en: 'Unopened insulin should be stored in the refrigerator (36-46°F). Once opened, insulin pens can be kept at room temperature for up to 28 days. Never freeze insulin. Keep it away from direct sunlight and heat.', es: 'La insulina sin abrir debe guardarse en el refrigerador (2-8°C). Una vez abierta, las plumas de insulina pueden mantenerse a temperatura ambiente hasta 28 días. Nunca congele la insulina. Manténgala alejada de la luz solar directa y el calor.' },
    },
    {
      id: 'faq-5',
      question: { en: 'Can my child go to school/daycare?', es: '¿Puede mi hijo/a ir a la escuela/guardería?' },
      answer: { en: 'Yes! Work with the school nurse to create a Diabetes Medical Management Plan (DMMP). The school must provide accommodations. CHOC has a school re-entry program — ask your care coordinator. Bring supplies: glucometer, test strips, juice boxes, and emergency contacts.', es: 'Sí. Trabaje con la enfermera escolar para crear un Plan de Manejo Médico de Diabetes. La escuela debe proporcionar adaptaciones. CHOC tiene un programa de reingreso escolar — pregunte a su coordinador de cuidado. Lleve suministros: glucómetro, tiras de prueba, jugos y contactos de emergencia.' },
    },
    {
      id: 'faq-6',
      question: { en: 'What if I can\'t afford supplies?', es: '¿Qué pasa si no puedo pagar los suministros?' },
      answer: { en: 'Several programs can help. Ask your social worker about Medi-Cal, the CHOC financial assistance program, and manufacturer patient assistance programs for insulin. Rite Aid Pharmacy also has a discount program. See the Social Resources tab for more options.', es: 'Varios programas pueden ayudar. Pregunte a su trabajador/a social sobre Medi-Cal, el programa de asistencia financiera de CHOC y los programas de asistencia al paciente de los fabricantes de insulina. Rite Aid Pharmacy también tiene un programa de descuentos. Vea la pestaña de Recursos Sociales para más opciones.' },
    },
    {
      id: 'faq-7',
      question: { en: 'When is my child\'s next appointment?', es: '¿Cuándo es la próxima cita de mi hijo/a?' },
      answer: { en: 'Your next follow-up is an Endocrinology Visit on May 8, 2026 at 10:00 AM with Dr. Flores at CHOC Endocrine Clinic. Check the Appointments tab for full details and directions.', es: 'Su próxima cita es una Visita de Endocrinología el 8 de mayo de 2026 a las 10:00 AM con Dr. Flores en la Clínica de Endocrinología de CHOC. Vea la pestaña de Citas para detalles completos y direcciones.' },
    },
  ],

  /* ── Social Resources ── */
  socialResources: [
    {
      id: 'soc-1',
      name: 'WIC (Women, Infants & Children)',
      category: 'food',
      description: { en: 'Free healthy foods, nutrition education, and breastfeeding support for pregnant and postpartum women, infants, and children up to age 5.', es: 'Alimentos saludables gratuitos, educación nutricional y apoyo para la lactancia para mujeres embarazadas y posparto, bebés y niños hasta los 5 años.' },
      eligibility: { en: 'Income at or below 185% of federal poverty level. Medi-Cal recipients automatically qualify.', es: 'Ingresos iguales o inferiores al 185% del nivel federal de pobreza. Los beneficiarios de Medi-Cal califican automáticamente.' },
      phone: '(714) 834-8075',
      website: 'https://www.ochealthinfo.com/wic',
      howToApply: { en: 'Call to schedule an appointment. Bring proof of identity, address, and income.', es: 'Llame para programar una cita. Traiga prueba de identidad, dirección e ingresos.' },
      languages: ['English', 'Spanish', 'Vietnamese'],
    },
    {
      id: 'soc-2',
      name: 'CalFresh (SNAP/Food Stamps)',
      category: 'food',
      description: { en: 'Monthly food benefits loaded onto an EBT card for groceries. Families with children who have medical conditions may qualify for additional benefits.', es: 'Beneficios mensuales de alimentos cargados en una tarjeta EBT para compras. Familias con niños con condiciones médicas pueden calificar para beneficios adicionales.' },
      eligibility: { en: 'Based on household size and income. A family of 3 earning under $2,311/month typically qualifies.', es: 'Basado en el tamaño del hogar e ingresos. Una familia de 3 que gana menos de $2,311/mes generalmente califica.' },
      phone: '(800) 281-9799',
      website: 'https://www.getcalfresh.org',
      howToApply: { en: 'Apply online at GetCalFresh.org or call the helpline. Processing takes up to 30 days.', es: 'Aplique en línea en GetCalFresh.org o llame a la línea de ayuda. El procesamiento toma hasta 30 días.' },
      languages: ['English', 'Spanish', 'Chinese', 'Vietnamese'],
    },
    {
      id: 'soc-3',
      name: 'Second Harvest Food Bank of OC',
      category: 'food',
      description: { en: 'Free groceries distributed through community pantries across Orange County. No documentation or proof of income required.', es: 'Alimentos gratuitos distribuidos a través de despensas comunitarias en el Condado de Orange. No se requiere documentación ni prueba de ingresos.' },
      eligibility: { en: 'Open to all Orange County residents. No ID or documentation needed.', es: 'Abierto a todos los residentes del Condado de Orange. No se necesita identificación ni documentación.' },
      phone: '(949) 653-2900',
      website: 'https://www.feedoc.org',
      howToApply: { en: 'Find a pantry near you at feedoc.org/find-food. Just show up during distribution hours.', es: 'Encuentre una despensa cerca de usted en feedoc.org/find-food. Solo preséntese durante las horas de distribución.' },
      languages: ['English', 'Spanish', 'Vietnamese', 'Korean'],
    },
    {
      id: 'soc-4',
      name: 'Medi-Cal',
      category: 'financial',
      description: { en: 'Free or low-cost health insurance covering doctor visits, hospital stays, prescriptions, mental health, dental, and vision for qualifying families.', es: 'Seguro de salud gratuito o de bajo costo que cubre visitas al médico, hospitalizaciones, recetas, salud mental, dental y visión para familias que califican.' },
      eligibility: { en: 'Children in families earning up to 266% of federal poverty level qualify. Children under 19 qualify regardless of immigration status.', es: 'Niños en familias que ganan hasta el 266% del nivel federal de pobreza califican. Niños menores de 19 años califican sin importar el estatus migratorio.' },
      phone: '(800) 786-0711',
      website: 'https://www.coveredca.com',
      howToApply: { en: 'Apply online at CoveredCA.com, by phone, or in person at your local social services office.', es: 'Aplique en línea en CoveredCA.com, por teléfono o en persona en su oficina local de servicios sociales.' },
      languages: ['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean'],
    },
    {
      id: 'soc-5',
      name: 'CHOC Financial Assistance',
      category: 'financial',
      description: { en: 'CHOC offers financial assistance for families who cannot pay their hospital bills. Covers partial or full charges based on income.', es: 'CHOC ofrece asistencia financiera para familias que no pueden pagar sus facturas hospitalarias. Cubre cargos parciales o totales según el ingreso.' },
      eligibility: { en: 'Families with income up to 400% of federal poverty level may qualify for reduced or free care.', es: 'Familias con ingresos hasta el 400% del nivel federal de pobreza pueden calificar para atención reducida o gratuita.' },
      phone: '(714) 509-8524',
      website: 'https://www.choc.org/patients-families/billing',
      howToApply: { en: 'Ask your social worker or call CHOC billing directly. They will help you complete the application.', es: 'Pregunte a su trabajador/a social o llame directamente a facturación de CHOC. Le ayudarán a completar la solicitud.' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'soc-6',
      name: 'Insulin Patient Assistance Programs',
      category: 'diabetes',
      description: { en: 'Eli Lilly (Lantus/Humalog manufacturer) offers free or reduced-cost insulin for qualifying patients without adequate insurance coverage.', es: 'Eli Lilly (fabricante de Lantus/Humalog) ofrece insulina gratuita o a costo reducido para pacientes que califican sin cobertura de seguro adecuada.' },
      eligibility: { en: 'Uninsured or underinsured patients. Income-based qualification varies by program.', es: 'Pacientes sin seguro o con seguro insuficiente. La calificación basada en ingresos varía según el programa.' },
      phone: '(800) 545-6962',
      website: 'https://www.lillycares.com',
      howToApply: { en: 'Call Lilly Cares or visit lillycares.com. Your doctor will need to complete part of the application.', es: 'Llame a Lilly Cares o visite lillycares.com. Su médico necesitará completar parte de la solicitud.' },
      languages: ['English', 'Spanish'],
    },
    {
      id: 'soc-7',
      name: '211 Orange County',
      category: 'housing',
      description: { en: 'Free referral service connecting families to housing, utility assistance, childcare, legal aid, and other social services across Orange County.', es: 'Servicio de referencia gratuito que conecta a familias con vivienda, asistencia de servicios públicos, cuidado infantil, ayuda legal y otros servicios sociales en el Condado de Orange.' },
      eligibility: { en: 'Open to all. No documentation required. Confidential.', es: 'Abierto a todos. No se requiere documentación. Confidencial.' },
      phone: '211',
      website: 'https://www.211oc.org',
      howToApply: { en: 'Dial 2-1-1 from any phone, 24/7. A specialist will assess your needs and provide referrals.', es: 'Marque 2-1-1 desde cualquier teléfono, 24/7. Un especialista evaluará sus necesidades y proporcionará referencias.' },
      languages: ['English', 'Spanish', '150+ languages via interpreter'],
    },
  ],
};
